version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: '04:00'
    timezone: Europe/Copenhagen
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: '04:00'
    timezone: Europe/Copenhagen
  versioning-strategy: increase
