site_name: DDF/DPL Documentation

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  font: false

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - content.code.copy
    - content.code.annotate

  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - def_list
  - footnotes
  - meta
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - tables

plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: yes
      # if set the docs directory will not be removed when importing docs.
      # When using this with a nav section in an imported repo you must keep the
      # docs directory in the path (e.g., docs/path/to/file.md).
      keep_docs_dir: false
      repos:
          # There will be a navigation section with this section name
        - section: DPL CMS
          # you can define the edit uri path
          import_url: 'https://github.com/danskernesdigitalebibliotek/dpl-cms?branch=develop'
        - section: DPL Design System
          # you can define the edit uri path
          import_url: 'https://github.com/danskernesdigitalebibliotek/dpl-design-system?branch=develop'
        - section: DPL Platform
          # you can define the edit uri path
          import_url: 'https://github.com/danskernesdigitalebibliotek/dpl-platform?branch=main'
        - section: DPL React
          # you can define the edit uri path
          import_url: 'https://github.com/danskernesdigitalebibliotek/dpl-react?branch=develop'
        - section: DPL Go
          # you can define the edit uri path
          import_url: 'https://github.com/danskernesdigitalebibliotek/dpl-go?branch=main'

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/det-digitale-folkebibliotek

repo_url: https://github.com/danskernesdigitalebibliotek
